---
title: ""
format: pdf
editor: visual
author: 
- Radiah Khan
- Mercer Mercer
- Nafisa Mohamed
- Catherine Weeks
---

```{r}
library(tidyverse)
library(broom)
library(readr)
School_Year_2022_2023_Statewide_Accountability_Ratings_20251119 <- read_csv("School_Year_2022-2023_Statewide_Accountability_Ratings_20251119.csv")
#View(School_Year_2022_2023_Statewide_Accountability_Ratings_20251119)
```

```{r}
library(janitor)
cleaned_name_school <- clean_names(School_Year_2022_2023_Statewide_Accountability_Ratings_20251119)
```

```{r}
colnames(cleaned_name_school)
```

```{r}
#Economically disadvantaged grouped by regions 
library(tidyverse)
data <-cleaned_name_school |>
  mutate(percent_economically_disadvantaged = 
           as.numeric(str_replace_all(percent_economically_disadvantaged, "[^0-9.]", "")))
```

```{r}
plot_economical_region <- data |>
 select(district , percent_economically_disadvantaged)|>
  group_by(district) |>
  summarise(avg_disadvantaged = mean(percent_economically_disadvantaged, na.rm = TRUE)) |>
  arrange((avg_disadvantaged))
plot_economical_region
```

#Variables

#Filtering it to 9-12

```{r}
filtered_df <- data |>
  filter(grades_served == "09 - 12")
filtered_df
```

```{r}
filtered_df_pivoted <- filtered_df |>
  pivot_longer(
    cols = starts_with("distinction_"),
    values_to = "distinction_status",
    names_to  = "Distinction Type"
  ) 
filtered_df_pivoted
```

```{r}
colnames(filtered_df_pivoted)
```

```{r}
final_df <- filtered_df_pivoted |>
  group_by(campus, district) |>
  summarise(
    number_of_students = first(number_of_students), #to get the unique values
    academic_growth_score = first(academic_growth_score),
    percent_economically_disadvantaged = first(percent_economically_disadvantaged),
    overall_score = first(overall_score),
    school_progress_score = first(school_progress_score),
    distinction_score = sum(distinction_status  == "Earned", na.rm = TRUE),
    .groups = "drop"
  )
final_df

```

There were 1394 data Now 1356 #Model Selection

```{r}
final_df[final_df == "."] <- NA

```

```{r}
final_df$overall_score <- as.numeric(final_df$overall_score)

```

```{r}
final_df <- final_df|>
  filter(
    !is.na(overall_score))

```

```{r}
na_values <- which(! complete.cases(final_df))

final_df <- final_df[complete.cases(final_df),]

```


```{r}
colnames(final_df)
```

#Model and nested model #Nested Model : #Automated selection

```{r}
final_df$academic_growth_score <- as.numeric(final_df$academic_growth_score)
final_df$distinction_score <- as.numeric(final_df$distinction_score)
final_df$school_progress_score<- as.numeric(final_df$school_progress_score)
final_df$percent_economically_disadvantaged<- as.numeric(final_df$percent_economically_disadvantaged)
final_df$number_of_students<- as.numeric(final_df$number_of_students)
```

```{r}
#Unlogged
#this one is better
reduced_model <-
  lm(overall_score ~ academic_growth_score+distinction_score+ school_progress_score, data = final_df )
summary(reduced_model)
plot(reduced_model)

```

```{r}
#logged
#the logged model is worse.
reduced_model_logged <-
  lm(log(overall_score) ~ academic_growth_score+distinction_score+ school_progress_score, data = final_df )
summary(reduced_model_logged)
```

```{r}
plot(reduced_model_logged)
```

```{r}
full_model <- 
  lm(overall_score ~ academic_growth_score+distinction_score+ school_progress_score + percent_economically_disadvantaged+number_of_students, data = final_df )
summary(full_model)
```

```{r}
plot(full_model)
```

```{r}
ggplot(reduced_model |> augment(), aes(x= .fitted, y = .resid)) +
  geom_point()+
  geom_hline(yintercept = 0, col ="red") +
  labs(title =  "xx",
       x = "xx",
       y= "yY") +
  theme_minimal()
```

#Model Selection

```{r}
#Forward --> AIC metric
step(reduced_model, scope = list(lower = reduced_model,
                                 upper = full_model),
     direction = "forward")
```

```{r}
reduced_model |>
  glance()
```

```{r}
full_model |>
  glance()
```

```{r}
library(car)
vif(reduced_model)
vif(full_model)

```

#Influential points

```{r}
influence <- augment(full_model)

influence <- influence |> mutate(row_id = row_number())

```

```{r}
k_plus_one <- length(coef(full_model))
n <- nrow(final_df)

# Filtering the data to view observations with high leverage
influence |> filter(.hat > 2 * k_plus_one/n)
leverage_index <- influence |> filter(.hat > 2 * k_plus_one/n) |> select(row_id) |> pull()
save <- final_df[leverage_index,]
augment_df<-influence[leverage_index,]

save$row_id <- leverage_index

augment_df<- augment_df |> left_join(save|>select(campus, district,row_id), join_by("row_id"=="row_id"))

```

```{r}
##std residuals
augment_df1<-augment_df |> filter(.std.resid < -2 | .std.resid > 2)
std_resid_id <- augment_df |> filter(.std.resid < -2 | .std.resid > 2) |> select(row_id) |> pull()
```

```{r}
#dont run this again. This is indexed so it will remove the wrong stuff if you do
final_df <-final_df[-1130,]
final_df <-final_df[-892,]
final_df <-final_df[-389, ]
final_df <-final_df[-333, ]
```


```{r}
new_model <- lm(overall_score ~ academic_growth_score+distinction_score+ school_progress_score + percent_economically_disadvantaged+number_of_students, data = final_df )
summary(new_model)
```





